/** This is free and unencumbered software released into the public domain.
    Anyone is free to copy, modify, publish, use, compile, sell, or
    distribute this software, either in source code form or as a compiled
    binary, for any purpose, commercial or non-commercial, and by any
    means.  **/
/*------------------------------------------------------------------------
    File        : TalkStatusEnum
    Description : 
    Author(s)   : pjudge
    Created     : 2017-10-02
    Notes       : 
  ----------------------------------------------------------------------*/
enum Conference.BusinessLogic.TalkStatusEnum :
    define enum Submitted
                UnderReview
                Accepted
                Rejected
                Scheduled
                .
end enum.